plugins:
  - jekyll-feed
  - jekyll-sitemap

title: Chemobrionics Database
languageCode: en-us

url: https://cpimentelguerra.com/new-chemDB/

permalink: /new-chemDB/:year/:month/:day/:title:output_ext
